apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bitcoin-pod
  name: bitcoin-pod
spec:
  containers:
    - image: ruimarinho/bitcoin-core:22.0
      name: bitcoin-pod
      command:
        - sh
      args:
        - -c
        - "sleep 1d"
      securityContext:
        runAsUser: 999
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true

  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

